version: "3.9"

services:
  php-cli:
    container_name: php-cli
    image: kata-cli
    build:
      context: .docker/php
      args:
        - INSTALL_INTL=true
        - INSTALL_YAML=true
        - INSTALL_XDEBUG=true
    volumes:
      - .docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./:/var/www
